# -*- coding: utf-8 -*-
"""Como gravar dados?

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h7JAlqZ7v83zzmlgD67tKFP7jnmPcV4i

# Como gravar dados?
"""

# Você pode usar quaisquer palavras para gravar, todavia recomendo "o que faz sentido", veja abaixo:

Nome = 'Jeiel'

Curso = 'Digital Security'

Idade = '17'

Universidade = 'Unama'

# Após ter executado, percebe-se que nada aconteceu, isso porque ele já gravou os dados. Agora veja o que acontece quando uso os dados já gravados:

print('Olá! Meu nome é', Nome ,'e tenho', Idade ,'anos de idade. Faço curso de', Curso ,'na Universidade', Universidade ,'.')

# Veja que ele substituiu 'Nome', 'Curso', 'Idade' e 'Universidade' pelas 'Jeiel', 'Digital Security', 'Idade' e 'Unama'. Isso facilita muito quando usas algo como "Database" na mesma plataforma.



"""[GitHub - Autor](https://github.com/Jeiel17)"""