# -*- coding: utf-8 -*-
"""Qual meu sistema operacional?

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WhVYzb_-_z00lZHE-K17y7YIfb7pNp5O

Para saber qual seu sistema operacional digite os sequintes comandos:
"""

import os

# Ao importar o "OS = Sistema Operacional", você deve prosseguir o seguinte comando para excutar qual OS estás usando:

os.name

# No meu dispositivo foi "posix", a qual se refere ao sistema Linux, caso seu seja "NT", se refere ao Windows.

"""Existe outra forma de saber seu sistema operacional, veja abaixo:"""

import platform
platform.system()

# Veja que neste formato foi bem direto ao dizer "Linux" do que "Posix".

"""___

[GitHub - Autor](https://github.com/Jeiel17)
"""